# Generated by Django 4.2.30 on 2026-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dailystat_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reporter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
